# -*- coding: utf-8 -*-
"""HW3 Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QtAQRq3pAX6i6kB_ThosJenzKlnd7Ud0

Q 3.1
"""

import pandas as pd
df_ILI=pd.read_csv('/content/ILINet_states.csv')

df_IA=pd.concat([df_ILI[(df_ILI['REGION']=='Iowa') & (df_ILI['YEAR']==2018) & (df_ILI['WEEK']>=40)],df_ILI[(df_ILI['REGION']=='Iowa') & (df_ILI['YEAR']==2019) & (df_ILI['WEEK']<=20)]],axis=0)

df_IA['Epiweek']=[(i+1) for i in range(len(df_IA))]

ep=df_IA['Epiweek'].tolist()
val=df_IA['%UNWEIGHTED ILI'].tolist()
for i in range(len(val)):
  val[i]=float(val[i])

import matplotlib.pyplot as plt
#sline = plt.plot("t","S","",data=sis_out,color="blue",linewidth=2)
plt.plot(ep,val)
#rline = plt.plot("t","R","",data=sir_out,color="blue",linewidth=2)
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("% Unweighted ILI",fontweight="bold")
#legend = plt.legend(title="Population",loc=5,bbox_to_anchor=(1.25,0.5))
plt.savefig('unw.png')

"""Q 3.2"""

df_2018_symptoms=pd.read_csv('/content/2018_symptoms_dataset.csv',date_parser=['date'])

df_2018_symptoms_IA=df_2018_symptoms[(df_2018_symptoms['sub_region_1']=='Iowa') & (df_2018_symptoms['date']>='2018-10-01') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]

df_2019_symptoms=pd.read_csv('/content/2019_weekly_symptoms_dataset.csv',date_parser=['date'])

df_2019_symptoms_IA=df_2019_symptoms[(df_2019_symptoms['sub_region_1']=='Iowa') & (df_2019_symptoms['date']<='2019-05-13') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]

IA_symp=pd.concat([df_2018_symptoms_IA,df_2019_symptoms_IA],axis=0)

fig, ax = plt.subplots()
ax.plot(range(len(IA_symp)),IA_symp['symptom:Cough'],label='Cough')
ax.plot(range(len(IA_symp)),IA_symp['symptom:Fatigue'],label='Fatigue')
ax.plot(range(len(IA_symp)),IA_symp['symptom:Fever'],label='Fever')
ax.plot(range(len(IA_symp)),IA_symp['symptom:Low-grade fever'],label='Low-Grade Fever')
ax.plot(range(len(IA_symp)),IA_symp['symptom:Sore throat'],label='Sore Throat')
ax.plot(range(len(IA_symp)),IA_symp['symptom:Headache'],label='Headache')
ax.plot(range(len(IA_symp)),IA_symp['symptom:Muscle weakness'],label='Muscle Weakness')
ax.legend(loc = 'upper right')
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("Symptoms",fontweight="bold")
#plt.show()
plt.savefig('symp_IA.png')

IA_symp['Epiweek']=[(i+1) for i in range(len(IA_symp))]

"""Q 3.3"""

IA_whole=pd.merge(df_IA,IA_symp,on='Epiweek')
IA_whole=IA_whole.drop(['date'],axis=1)
IA_whole['%UNWEIGHTED ILI']=IA_whole['%UNWEIGHTED ILI'].astype(float)

checker=['symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']

from scipy import stats
for c in checker:
  print(c)
  print(stats.pearsonr(IA_whole['%UNWEIGHTED ILI'],IA_whole[c]))
lead_times={}
for t in range(len(IA_whole)):
  ILI=IA_whole['%UNWEIGHTED ILI'].tolist()[(t):(len(IA_whole))]
  symp=IA_whole['symptom:Fever'].tolist()[0:(len(IA_whole)-t)]
  #print(len(ILI))
  #print(len(symp))
  if len(ILI)>1:
    lead_times[t],_=stats.pearsonr(ILI,symp)
max(lead_times, key=lead_times.get)

len(IA_whole)

"""Q 3.4"""

df_CA=pd.concat([df_ILI[(df_ILI['REGION']=='California') & (df_ILI['YEAR']==2018) & (df_ILI['WEEK']>=40)],df_ILI[(df_ILI['REGION']=='California') & (df_ILI['YEAR']==2019) & (df_ILI['WEEK']<=20)]],axis=0)
df_CA['Epiweek']=[(i+1) for i in range(len(df_CA))]
ep=df_CA['Epiweek'].tolist()
val=df_CA['%UNWEIGHTED ILI'].tolist()
for i in range(len(val)):
  val[i]=float(val[i])
import matplotlib.pyplot as plt
#sline = plt.plot("t","S","",data=sis_out,color="blue",linewidth=2)
plt.plot(ep,val)
#rline = plt.plot("t","R","",data=sir_out,color="blue",linewidth=2)
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("% Unweighted ILI",fontweight="bold")
#legend = plt.legend(title="Population",loc=5,bbox_to_anchor=(1.25,0.5))
plt.savefig('unw_CA.png')
df_2018_symptoms_CA=df_2018_symptoms[(df_2018_symptoms['sub_region_1']=='California') & (df_2018_symptoms['date']>='2018-10-01') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
df_2019_symptoms_CA=df_2019_symptoms[(df_2019_symptoms['sub_region_1']=='California') & (df_2019_symptoms['date']<='2019-05-13') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
CA_symp=pd.concat([df_2018_symptoms_CA,df_2019_symptoms_CA],axis=0)
fig, ax = plt.subplots()
ax.plot(range(len(CA_symp)),CA_symp['symptom:Cough'],label='Cough')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fatigue'],label='Fatigue')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fever'],label='Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Low-grade fever'],label='Low-Grade Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Sore throat'],label='Sore Throat')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Headache'],label='Headache')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Muscle weakness'],label='Muscle Weakness')
ax.legend(loc = 'upper right')
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("Symptoms",fontweight="bold")
#plt.show()
plt.savefig('symp_CA.png')
CA_symp['Epiweek']=[(i+1) for i in range(len(CA_symp))]
CA_whole=pd.merge(df_CA,CA_symp,on='Epiweek')
CA_whole=CA_whole.drop(['date'],axis=1)
CA_whole['%UNWEIGHTED ILI']=CA_whole['%UNWEIGHTED ILI'].astype(float)
from scipy import stats
for c in checker:
  print(c)
  print(stats.pearsonr(CA_whole['%UNWEIGHTED ILI'],CA_whole[c]))
lead_times={}
for t in range(len(CA_whole)):
  ILI=CA_whole['%UNWEIGHTED ILI'].tolist()[(t):(len(CA_whole))]
  symp=CA_whole['symptom:Cough'].tolist()[0:(len(CA_whole)-t)]
  #print(len(ILI))
  #print(len(symp))
  if len(ILI)>1:
    lead_times[t],_=stats.pearsonr(ILI,symp)
max(lead_times, key=lead_times.get)

df_CA=pd.concat([df_ILI[(df_ILI['REGION']=='Texas') & (df_ILI['YEAR']==2018) & (df_ILI['WEEK']>=40)],df_ILI[(df_ILI['REGION']=='Texas') & (df_ILI['YEAR']==2019) & (df_ILI['WEEK']<=20)]],axis=0)
df_CA['Epiweek']=[(i+1) for i in range(len(df_CA))]
ep=df_CA['Epiweek'].tolist()
val=df_CA['%UNWEIGHTED ILI'].tolist()
for i in range(len(val)):
  val[i]=float(val[i])
import matplotlib.pyplot as plt
#sline = plt.plot("t","S","",data=sis_out,color="blue",linewidth=2)
plt.plot(ep,val)
#rline = plt.plot("t","R","",data=sir_out,color="blue",linewidth=2)
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("% Unweighted ILI",fontweight="bold")
#legend = plt.legend(title="Population",loc=5,bbox_to_anchor=(1.25,0.5))
plt.savefig('unw_TX.png')
df_2018_symptoms_CA=df_2018_symptoms[(df_2018_symptoms['sub_region_1']=='Texas') & (df_2018_symptoms['date']>='2018-10-01') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
df_2019_symptoms_CA=df_2019_symptoms[(df_2019_symptoms['sub_region_1']=='Texas') & (df_2019_symptoms['date']<='2019-05-13') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
CA_symp=pd.concat([df_2018_symptoms_CA,df_2019_symptoms_CA],axis=0)
fig, ax = plt.subplots()
ax.plot(range(len(CA_symp)),CA_symp['symptom:Cough'],label='Cough')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fatigue'],label='Fatigue')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fever'],label='Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Low-grade fever'],label='Low-Grade Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Sore throat'],label='Sore Throat')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Headache'],label='Headache')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Muscle weakness'],label='Muscle Weakness')
ax.legend(loc = 'upper right')
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("Symptoms",fontweight="bold")
#plt.show()
plt.savefig('symp_TX.png')
CA_symp['Epiweek']=[(i+1) for i in range(len(CA_symp))]
CA_whole=pd.merge(df_CA,CA_symp,on='Epiweek')
CA_whole=CA_whole.drop(['date'],axis=1)
CA_whole['%UNWEIGHTED ILI']=CA_whole['%UNWEIGHTED ILI'].astype(float)
from scipy import stats
for c in checker:
  print(c)
  print(stats.pearsonr(CA_whole['%UNWEIGHTED ILI'],CA_whole[c]))
lead_times={}
for t in range(len(CA_whole)):
  ILI=CA_whole['%UNWEIGHTED ILI'].tolist()[(t):(len(CA_whole))]
  symp=CA_whole['symptom:Muscle weakness'].tolist()[0:(len(CA_whole)-t)]
  #print(len(ILI))
  #print(len(symp))
  if len(ILI)>1:
    lead_times[t],_=stats.pearsonr(ILI,symp)
max(lead_times, key=lead_times.get)

df_CA=pd.concat([df_ILI[(df_ILI['REGION']=='New York') & (df_ILI['YEAR']==2018) & (df_ILI['WEEK']>=40)],df_ILI[(df_ILI['REGION']=='New York') & (df_ILI['YEAR']==2019) & (df_ILI['WEEK']<=20)]],axis=0)
df_CA['Epiweek']=[(i+1) for i in range(len(df_CA))]
ep=df_CA['Epiweek'].tolist()
val=df_CA['%UNWEIGHTED ILI'].tolist()
for i in range(len(val)):
  val[i]=float(val[i])
import matplotlib.pyplot as plt
#sline = plt.plot("t","S","",data=sis_out,color="blue",linewidth=2)
plt.plot(ep,val)
#rline = plt.plot("t","R","",data=sir_out,color="blue",linewidth=2)
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("% Unweighted ILI",fontweight="bold")
#legend = plt.legend(title="Population",loc=5,bbox_to_anchor=(1.25,0.5))
plt.savefig('unw_NY.png')
df_2018_symptoms_CA=df_2018_symptoms[(df_2018_symptoms['sub_region_1']=='New York') & (df_2018_symptoms['date']>='2018-10-01') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
df_2019_symptoms_CA=df_2019_symptoms[(df_2019_symptoms['sub_region_1']=='New York') & (df_2019_symptoms['date']<='2019-05-13') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
CA_symp=pd.concat([df_2018_symptoms_CA,df_2019_symptoms_CA],axis=0)
fig, ax = plt.subplots()
ax.plot(range(len(CA_symp)),CA_symp['symptom:Cough'],label='Cough')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fatigue'],label='Fatigue')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fever'],label='Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Low-grade fever'],label='Low-Grade Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Sore throat'],label='Sore Throat')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Headache'],label='Headache')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Muscle weakness'],label='Muscle Weakness')
ax.legend(loc = 'upper right')
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("Symptoms",fontweight="bold")
#plt.show()
plt.savefig('symp_NY.png')
CA_symp['Epiweek']=[(i+1) for i in range(len(CA_symp))]
CA_whole=pd.merge(df_CA,CA_symp,on='Epiweek')
CA_whole=CA_whole.drop(['date'],axis=1)
CA_whole['%UNWEIGHTED ILI']=CA_whole['%UNWEIGHTED ILI'].astype(float)
from scipy import stats
for c in checker:
  print(c)
  print(stats.pearsonr(CA_whole['%UNWEIGHTED ILI'],CA_whole[c]))
lead_times={}
for t in range(len(CA_whole)):
  ILI=CA_whole['%UNWEIGHTED ILI'].tolist()[(t):(len(CA_whole))]
  symp=CA_whole['symptom:Low-grade fever'].tolist()[0:(len(CA_whole)-t)]
  #print(len(ILI))
  #print(len(symp))
  if len(ILI)>1:
    lead_times[t],_=stats.pearsonr(ILI,symp)
max(lead_times, key=lead_times.get)

df_CA=pd.concat([df_ILI[(df_ILI['REGION']=='Alaska') & (df_ILI['YEAR']==2018) & (df_ILI['WEEK']>=40)],df_ILI[(df_ILI['REGION']=='Alaska') & (df_ILI['YEAR']==2019) & (df_ILI['WEEK']<=20)]],axis=0)
df_CA['Epiweek']=[(i+1) for i in range(len(df_CA))]
ep=df_CA['Epiweek'].tolist()
val=df_CA['%UNWEIGHTED ILI'].tolist()
for i in range(len(val)):
  val[i]=float(val[i])
import matplotlib.pyplot as plt
#sline = plt.plot("t","S","",data=sis_out,color="blue",linewidth=2)
plt.plot(ep,val)
#rline = plt.plot("t","R","",data=sir_out,color="blue",linewidth=2)
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("% Unweighted ILI",fontweight="bold")
#legend = plt.legend(title="Population",loc=5,bbox_to_anchor=(1.25,0.5))
plt.savefig('unw_AL.png')
df_2018_symptoms_CA=df_2018_symptoms[(df_2018_symptoms['sub_region_1']=='Alaska') & (df_2018_symptoms['date']>='2018-10-01') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
df_2019_symptoms_CA=df_2019_symptoms[(df_2019_symptoms['sub_region_1']=='Alaska') & (df_2019_symptoms['date']<='2019-05-13') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
CA_symp=pd.concat([df_2018_symptoms_CA,df_2019_symptoms_CA],axis=0)
fig, ax = plt.subplots()
ax.plot(range(len(CA_symp)),CA_symp['symptom:Cough'],label='Cough')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fatigue'],label='Fatigue')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fever'],label='Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Low-grade fever'],label='Low-Grade Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Sore throat'],label='Sore Throat')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Headache'],label='Headache')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Muscle weakness'],label='Muscle Weakness')
ax.legend(loc = 'upper right')
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("Symptoms",fontweight="bold")
#plt.show()
plt.savefig('symp_AL.png')
CA_symp['Epiweek']=[(i+1) for i in range(len(CA_symp))]
CA_whole=pd.merge(df_CA,CA_symp,on='Epiweek')
CA_whole=CA_whole.drop(['date'],axis=1)
CA_whole['%UNWEIGHTED ILI']=CA_whole['%UNWEIGHTED ILI'].astype(float)
CA_whole=CA_whole.dropna()
from scipy import stats
for c in checker:
  print(c)
  print(stats.pearsonr(CA_whole['%UNWEIGHTED ILI'],CA_whole[c]))
lead_times={}
for t in range(len(CA_whole)):
  ILI=CA_whole['%UNWEIGHTED ILI'].tolist()[(t):(len(CA_whole))]
  symp=CA_whole['symptom:Cough'].tolist()[0:(len(CA_whole)-t)]
  #print(len(ILI))
  #print(len(symp))
  if len(ILI)>1:
    lead_times[t],_=stats.pearsonr(ILI,symp)
max(lead_times, key=lead_times.get)

df_CA=pd.concat([df_ILI[(df_ILI['REGION']=='Georgia') & (df_ILI['YEAR']==2018) & (df_ILI['WEEK']>=40)],df_ILI[(df_ILI['REGION']=='Georgia') & (df_ILI['YEAR']==2019) & (df_ILI['WEEK']<=20)]],axis=0)
df_CA['Epiweek']=[(i+1) for i in range(len(df_CA))]
ep=df_CA['Epiweek'].tolist()
val=df_CA['%UNWEIGHTED ILI'].tolist()
for i in range(len(val)):
  val[i]=float(val[i])
import matplotlib.pyplot as plt
#sline = plt.plot("t","S","",data=sis_out,color="blue",linewidth=2)
plt.plot(ep,val)
#rline = plt.plot("t","R","",data=sir_out,color="blue",linewidth=2)
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("% Unweighted ILI",fontweight="bold")
#legend = plt.legend(title="Population",loc=5,bbox_to_anchor=(1.25,0.5))
plt.savefig('unw_GA.png')
df_2018_symptoms_CA=df_2018_symptoms[(df_2018_symptoms['sub_region_1']=='Georgia') & (df_2018_symptoms['date']>='2018-10-01') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
df_2019_symptoms_CA=df_2019_symptoms[(df_2019_symptoms['sub_region_1']=='Georgia') & (df_2019_symptoms['date']<='2019-05-13') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
CA_symp=pd.concat([df_2018_symptoms_CA,df_2019_symptoms_CA],axis=0)
fig, ax = plt.subplots()
ax.plot(range(len(CA_symp)),CA_symp['symptom:Cough'],label='Cough')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fatigue'],label='Fatigue')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fever'],label='Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Low-grade fever'],label='Low-Grade Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Sore throat'],label='Sore Throat')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Headache'],label='Headache')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Muscle weakness'],label='Muscle Weakness')
ax.legend(loc = 'upper right')
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("Symptoms",fontweight="bold")
#plt.show()
plt.savefig('symp_GA.png')
CA_symp['Epiweek']=[(i+1) for i in range(len(CA_symp))]
CA_whole=pd.merge(df_CA,CA_symp,on='Epiweek')
CA_whole=CA_whole.drop(['date'],axis=1)
CA_whole['%UNWEIGHTED ILI']=CA_whole['%UNWEIGHTED ILI'].astype(float)
CA_whole=CA_whole.dropna()
from scipy import stats
for c in checker:
  print(c)
  print(stats.pearsonr(CA_whole['%UNWEIGHTED ILI'],CA_whole[c]))
lead_times={}
for t in range(len(CA_whole)):
  ILI=CA_whole['%UNWEIGHTED ILI'].tolist()[(t):(len(CA_whole))]
  symp=CA_whole['symptom:Cough'].tolist()[0:(len(CA_whole)-t)]
  #print(len(ILI))
  #print(len(symp))
  if len(ILI)>1:
    lead_times[t],_=stats.pearsonr(ILI,symp)
max(lead_times, key=lead_times.get)

df_CA=pd.concat([df_ILI[(df_ILI['REGION']=='Mississippi') & (df_ILI['YEAR']==2018) & (df_ILI['WEEK']>=40)],df_ILI[(df_ILI['REGION']=='Alaska') & (df_ILI['YEAR']==2019) & (df_ILI['WEEK']<=20)]],axis=0)
df_CA['Epiweek']=[(i+1) for i in range(len(df_CA))]
ep=df_CA['Epiweek'].tolist()
val=df_CA['%UNWEIGHTED ILI'].tolist()
for i in range(len(val)):
  val[i]=float(val[i])
import matplotlib.pyplot as plt
#sline = plt.plot("t","S","",data=sis_out,color="blue",linewidth=2)
plt.plot(ep,val)
#rline = plt.plot("t","R","",data=sir_out,color="blue",linewidth=2)
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("% Unweighted ILI",fontweight="bold")
#legend = plt.legend(title="Population",loc=5,bbox_to_anchor=(1.25,0.5))
plt.savefig('unw_MS.png')
df_2018_symptoms_CA=df_2018_symptoms[(df_2018_symptoms['sub_region_1']=='Mississippi') & (df_2018_symptoms['date']>='2018-10-01') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
df_2019_symptoms_CA=df_2019_symptoms[(df_2019_symptoms['sub_region_1']=='Mississippi') & (df_2019_symptoms['date']<='2019-05-13') ][['date','symptom:Fever','symptom:Low-grade fever','symptom:Cough','symptom:Sore throat','symptom:Headache','symptom:Fatigue','symptom:Muscle weakness']]
CA_symp=pd.concat([df_2018_symptoms_CA,df_2019_symptoms_CA],axis=0)
fig, ax = plt.subplots()
ax.plot(range(len(CA_symp)),CA_symp['symptom:Cough'],label='Cough')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fatigue'],label='Fatigue')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Fever'],label='Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Low-grade fever'],label='Low-Grade Fever')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Sore throat'],label='Sore Throat')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Headache'],label='Headache')
ax.plot(range(len(CA_symp)),CA_symp['symptom:Muscle weakness'],label='Muscle Weakness')
ax.legend(loc = 'upper right')
plt.xlabel("EpiWeek",fontweight="bold")
plt.ylabel("Symptoms",fontweight="bold")
#plt.show()
plt.savefig('symp_MS.png')
CA_symp['Epiweek']=[(i+1) for i in range(len(CA_symp))]
CA_whole=pd.merge(df_CA,CA_symp,on='Epiweek')
CA_whole=CA_whole.drop(['date'],axis=1)
CA_whole['%UNWEIGHTED ILI']=CA_whole['%UNWEIGHTED ILI'].astype(float)
CA_whole=CA_whole.dropna()
from scipy import stats
for c in checker:
  print(c)
  print(stats.pearsonr(CA_whole['%UNWEIGHTED ILI'],CA_whole[c]))
lead_times={}
for t in range(len(CA_whole)):
  ILI=CA_whole['%UNWEIGHTED ILI'].tolist()[(t):(len(CA_whole))]
  symp=CA_whole['symptom:Fever'].tolist()[0:(len(CA_whole)-t)]
  #print(len(ILI))
  #print(len(symp))
  if len(ILI)>1:
    lead_times[t],_=stats.pearsonr(ILI,symp)
max(lead_times, key=lead_times.get)