# -*- coding: utf-8 -*-
"""Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cJKw3H8i--DsSn6FIHFzGkogSBz2JTm5

A 3.1
"""

!pip install EoN

import networkx as nx
import EoN
import matplotlib.pyplot as plt

Graphtype=nx.Graph()   # use net.Graph() for undirected graph

# How to read from a file. Note: if your egde weights are int, 
# change float to int.
G = nx.read_edgelist(
    '/content/cayley.txt', 
    create_using=Graphtype,
    nodetype=int,
    data=(('weight',float),)
)

nx.draw(G,with_labels = True)

Ilist=[]
for i in range(100):
  full_data = EoN.fast_SIS(G, gamma=0, tau=0.2, tmax = 10,return_full_data=True,
                            initial_infecteds = 0)
  tran=full_data.transmissions()
  I=[]
  for j in range(len(tran)):
    dat=tran[j]
    if dat[1]==None:
      continue
    else:
      I.append(dat[1])
      I.append(dat[2])
  I=list(set(I))
  Ilist.append(I)

Ilist

file = open('3.1.txt','w')
for item in Ilist:
  for it in item:
	  file.write(str(it)+' ')
  file.write('\n')
file.close()

"""A 3.2"""

acc=0
for i in range(100):
  I=Ilist[i]
  H=G.subgraph(I)
  #nx.draw(H)
  S=list(nx.center(H))
  if len(S)==1:
    if 0 in S:
      acc+=1

acc_per=acc/100
acc_per #0.65

"""3.3"""

Ilist=[]
for i in range(100):
  full_data = EoN.fast_SIS(G, gamma=0, tau=0.2, tmax = 10,return_full_data=True,
                            initial_infecteds = 1)
  tran=full_data.transmissions()
  I=[]
  for j in range(len(tran)):
    dat=tran[j]
    if dat[1]==None:
      continue
    else:
      I.append(dat[1])
      I.append(dat[2])
  I=list(set(I))
  Ilist.append(I)

file = open('3.3.txt','w')
for item in Ilist:
  for it in item:
	  file.write(str(it)+' ')
  file.write('\n')
file.close()

acc=0
for i in range(100):
  I=Ilist[i]
  H=G.subgraph(I)
  #nx.draw(H)
  S=list(nx.center(H))
  if len(S)==1:
    if 0 in S:
      acc+=1

acc_per=acc/100
acc_per #0.43